Repository crowbar/crowbar, pull requests merged in 2019-02, with the labels that each got.

#2370 ipv6: Ensure ip version uniformatiy across networks
  scripts/network-json-validator
Labels: IPv6-CP

#2371 install-chef-suse: filter comments from authorized_keys file
  scripts/install-chef-suse.sh
Labels: needs backport to SOC7, needs backport to SOC8

#2374 [5.0] install-chef-suse: filter comments from authorized_keys file
  scripts/install-chef-suse.sh
Labels: backport from SOC9

#2373 [4.0] install-chef-suse: filter comments from authorized_keys file
  scripts/install-chef-suse.sh
Labels: backport from SOC9
